language: csharp
sudo: required
dist: trusty
env:
  global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
addons:
  apt:
    packages:
    - libunwind8
mono: none
os:
- linux
- osx
osx_image: xcode8.2
before_install:
- if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s
  /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  /usr/local/lib/; fi
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 8.9.4
  - nvm use 8.9.4
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel Current --version latest --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"
script:
  - pwd="`pwd`"
  - dotnet --info
  - dotnet restore
  - dotnet build src/Trail --configuration Release
  - dotnet build src/Trail.Flatware --configuration Release
  - dotnet build src/Trail.BlazorRedux --configuration Release
  - dotnet test test/Trail.Tests
  - dotnet pack src/Trail --configuration Release -o $pwd/bin
  - dotnet pack src/Trail.Flatware --configuration Release -o $pwd/bin
  - dotnet pack src/Trail.BlazorRedux --configuration Release -o $pwd/bin
